name: Terraform Verification

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform fmt check
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Run terraform fmt check
        run: |
          terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform validate check
    needs: terraform-fmt
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Initialize Terraform
        run: terraform init

      - name: Run terraform validate
        run: terraform validate
